# base docker-compose file
version: '3'
services:
  node-app:
    container_name: learn-docker #specify the name of the container
    image: learn-docker
    depends_on: # mongo and redis must be running first before running the node-app
      - mongo
      - redis
    ports:
      - '5500:5500'
    env_file:
      - ./.env
    restart: always

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test1234

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test1234
      ME_CONFIG_MONGODB_URL: mongodb://root:test1234@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount the nginx.conf file to the container

volumes:
  mongo-db:
