# base docker-compose file
version: '3'
services:
  node-app:
    container_name: learn-docker #specify the name of the container
    image: learn-docker
    ports:
      - '5500:5500'
    env_file:
      - ./.env

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test1234

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test1234
      ME_CONFIG_MONGODB_URL: mongodb://root:test1234@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-db:
